from __future__ import annotations

APP_NAME = "星期五"
MAX_TOOL_ROUNDS = 20
MAX_TOOL_RESULT_CHARS = 4000  # 写入上下文的工具结果预算（配合智能压缩）
TOOL_RESULT_HEAD_CHARS = 2400
TOOL_RESULT_TAIL_CHARS = 1200
TOOL_RESULT_ARCHIVE_CHARS = 900  # 历史 tool 消息归档压缩
MAX_PERSISTED_TOOL_CHARS = 400  # 落盘时 tool 消息内容上限
SESSION_FORMAT_VERSION = 2

# 前缀缓存 / append-only 上下文（Reasonix 式）
CONTEXT_COMPACT_RATIO = 0.80  # 达到上下文预算 80% 时触发折叠
CONTEXT_MIN_KEEP_RECENT = 6  # 折叠时保留最近 N 条（不含 system）
CONTEXT_COMPACT_BATCH = 10  # 每次折叠的消息条数
COMPACT_SUMMARY_MARKER = "[前文摘要 · 自动压缩]"

# 工具执行超时（秒）
TOOL_TIMEOUT_READ = 30
TOOL_TIMEOUT_VISION = 120
TOOL_TIMEOUT_IMAGE_GEN = 180
TOOL_TIMEOUT_WRITE = 60
TOOL_TIMEOUT_EXEC = 120
TOOL_TIMEOUT_DOWNLOAD = 900
TOOL_TIMEOUT_DOWNLOAD_LARGE = 3600
CANCEL_POLL_INTERVAL = 0.3  # 停止请求轮询间隔（秒）
VISION_HTTP_TIMEOUT = 90  # 视觉 API 单次 HTTP 读超时（秒）
IMAGE_GEN_HTTP_TIMEOUT = 180  # 生图 API 单次 HTTP 读超时（秒）

# 联网限制
WEB_PAGE_MAX_BYTES = 10 * 1024 * 1024
DOWNLOAD_MAX_BYTES = 2 * 1024 * 1024 * 1024
DOWNLOAD_LARGE_THRESHOLD_BYTES = 1024 * 1024 * 1024
DOWNLOAD_LARGE_MAX_BYTES = 10 * 1024 * 1024 * 1024

__all__ = [
    "APP_NAME",
    "MAX_TOOL_ROUNDS",
    "MAX_TOOL_RESULT_CHARS",
    "TOOL_RESULT_HEAD_CHARS",
    "TOOL_RESULT_TAIL_CHARS",
    "TOOL_RESULT_ARCHIVE_CHARS",
    "MAX_PERSISTED_TOOL_CHARS",
    "SESSION_FORMAT_VERSION",
    "CONTEXT_COMPACT_RATIO",
    "CONTEXT_MIN_KEEP_RECENT",
    "CONTEXT_COMPACT_BATCH",
    "COMPACT_SUMMARY_MARKER",
    "TOOL_TIMEOUT_READ",
    "TOOL_TIMEOUT_VISION",
    "TOOL_TIMEOUT_IMAGE_GEN",
    "TOOL_TIMEOUT_WRITE",
    "TOOL_TIMEOUT_EXEC",
    "TOOL_TIMEOUT_DOWNLOAD",
    "TOOL_TIMEOUT_DOWNLOAD_LARGE",
    "CANCEL_POLL_INTERVAL",
    "VISION_HTTP_TIMEOUT",
    "IMAGE_GEN_HTTP_TIMEOUT",
    "WEB_PAGE_MAX_BYTES",
    "DOWNLOAD_MAX_BYTES",
    "DOWNLOAD_LARGE_THRESHOLD_BYTES",
    "DOWNLOAD_LARGE_MAX_BYTES",
]
