from __future__ import annotations

APP_NAME = "星期五"
MAX_TOOL_ROUNDS = 20
MAX_TOOL_RESULT_CHARS = 2000  # 单次工具结果写入上下文的最大字符数
MAX_PERSISTED_TOOL_CHARS = 400  # 落盘时 tool 消息内容上限
SESSION_FORMAT_VERSION = 2

# 工具执行超时（秒）
TOOL_TIMEOUT_READ = 30
TOOL_TIMEOUT_VISION = 120
TOOL_TIMEOUT_IMAGE_GEN = 180
TOOL_TIMEOUT_WRITE = 60
TOOL_TIMEOUT_EXEC = 120
TOOL_TIMEOUT_DOWNLOAD = 900
TOOL_TIMEOUT_DOWNLOAD_LARGE = 3600
CANCEL_POLL_INTERVAL = 0.3  # 停止请求轮询间隔（秒）
VISION_HTTP_TIMEOUT = 90  # 视觉 API 单次 HTTP 读超时（秒）
IMAGE_GEN_HTTP_TIMEOUT = 180  # 生图 API 单次 HTTP 读超时（秒）

# 联网限制
WEB_PAGE_MAX_BYTES = 10 * 1024 * 1024
DOWNLOAD_MAX_BYTES = 2 * 1024 * 1024 * 1024
DOWNLOAD_LARGE_THRESHOLD_BYTES = 1024 * 1024 * 1024
DOWNLOAD_LARGE_MAX_BYTES = 10 * 1024 * 1024 * 1024

__all__ = [
    "APP_NAME",
    "MAX_TOOL_ROUNDS",
    "MAX_TOOL_RESULT_CHARS",
    "MAX_PERSISTED_TOOL_CHARS",
    "SESSION_FORMAT_VERSION",
    "TOOL_TIMEOUT_READ",
    "TOOL_TIMEOUT_VISION",
    "TOOL_TIMEOUT_IMAGE_GEN",
    "TOOL_TIMEOUT_WRITE",
    "TOOL_TIMEOUT_EXEC",
    "TOOL_TIMEOUT_DOWNLOAD",
    "TOOL_TIMEOUT_DOWNLOAD_LARGE",
    "CANCEL_POLL_INTERVAL",
    "VISION_HTTP_TIMEOUT",
    "IMAGE_GEN_HTTP_TIMEOUT",
    "WEB_PAGE_MAX_BYTES",
    "DOWNLOAD_MAX_BYTES",
    "DOWNLOAD_LARGE_THRESHOLD_BYTES",
    "DOWNLOAD_LARGE_MAX_BYTES",
]
